# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker build -f dockerfile . -t yahia90/gthub_action:v1.10
        
      - name: login
        run:  |
           docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: push
        run:  |
          docker push yahia90/gthub_action:v1.10
