name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: docker build -f Dockerfile . -t yahia90/gthub_action:v1.10
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOKER_USERNAME }}
          password: ${{ secrets.DOKER_PASSWORD }}
      - name: push
        run:  |
          docker push yahia90/gthub_action:v1.10
      - name: deploy
        run:  |
          docker run -d -p 20:20 yahia90/gthub_action:v1.10
          
          
     
          

