name: remote ssh command
on: [push]
jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using KEY
      uses: actions/checkout@v2
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }} 
        SSH_USERNAME: ${{ secrets.SSH_USRNAME }} 
        PORT: 22
        SSH_KEY: ${{ secrets.SSH_KEY }} 
      with:
          source: "/"
          target: "/home/ubuntu"   
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo chmod -R 755 /home/ubuntu
            sudo chown -R username:username /home/ubuntu
            sudo setfacl -R -m u:www-data:rwx /home/ubuntu 
            sudo mkdir please
                 
