name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using KEY
      uses: actions/checkout@v2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }} # ip-172-31-23-178
        SOURCE: /
        REMOTE_HOST: ${{ secrets.HOST }} # ubuntu@ip-172-31-23-178
        REMOTE_USER: ${{ secrets.SSH_USERNAME }} # key get from this path  ~/.ssh/id_rsa.pub
        PORT: ${{ secrets.PORT }} #default 22
        TARGET: ${{ secrets.TARGET_DIR }}
    - name: make dirctory
      run: |
         cd/  echo "::set-output name=result::$(pwd)/n"
   
                 
