name: remote ssh command
on: [push]
jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using KEY
      uses: actions/checkout@v2
      env:
        HOST_SHH: ${{ secrets.SSH_HOST }} 
        SSH_USERNAME: ${{ secrets.SSH_USRNAME }} 
        SSH_KEY: ${{ secrets.SSH_KEY }} 
      
      with:
        host: ${{ secrets.SSH_HOST }} 
        username: ${{ secrets.SSH_USRNAME }} 
        key: ${{ secrets.SSH_KEY }} 
        port: 22
        script: |    
            sudo mkdir /home/yahia/ahmed
                 
