name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using KEY
      uses: actions/checkout@v2
      env:
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }} 
        HOST: ${{ secrets.HOST }} 
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }} 
        PORT: ${{ secrets.PORT }}
        TARGET_DIR: ${{ secrets.TARGET_DIR }}
    - name: make dirctory
      run:  mkdir host
   
                 
