name: remote ssh command
on: [push]
jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using KEY
      uses: actions/checkout@v2
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }} 
        SSH_USERNAME: ${{ secrets.SSH_USRNAME }} 
        PORT: 22
        SSH_KEY: ${{ secrets.SSH_KEY }} 
        SOURCE: /
        TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |    
            sudo chmod -R 755 /home/ubuntu
            sudo chown -R yahia:yahia /home/ubuntu
            sudo mkdir hhhhh
                 
