name: remote ssh command
on:  [push]
  
jobs:
  job_on:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using KEY
      uses: actions/checkout@v2
      with:
        host: ip-172-31-22-159.ec2.internal
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |  
          whoami
          
