name: remote ssh command
on: [push]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cheackout the code
        uses: actions/checkout@v2
        
      - name: pass multiple environment
        uses: actions/checkout@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: /
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TAEGET: ${{ secrets.TARGET_DIR }}
      - name: echo
        run: 
               echo " hi "
      - name: pwd        
        run: | 
               pwd
      - name: mkdir       
        run: |        
              mkdir /home/ubuntu/test
      - name: cd       
        run: |  
            cd /
            
                
