name: remote ssh command
on: [push]
jobs:
  job_on:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy source-code
      uses: appleboy/ssh-action@master
      env:
          HOST: ${{ secrets.HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          PORT: 22
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      with:
          source: "*"
          target: "/home/ubuntu"
    - name: commands after deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |  
                echo " hi "
                pwd
                cd /
